auto:	          false
markdown:         rdiscount
pygments:         true

title: "HTML Dog 中文翻译"
description: "HTML, CSS, JavaScript 教程, 手册, 文章 | HTML Dog 中文翻译"
domain: yanguanglan.github.io
baseurl: /cnhtml/
production_url: http://yanguanglan.github.io/cnhtml/

author :
  lan : "Lan"
  julytalk: "Julytalk"

